"""
preprocess_empathetic.py  (v2 — datasets-server API)
──────────────────────────────────────────────────────
Downloads EmpatheticDialogues via the HuggingFace Datasets Server REST API.

Why previous versions failed
──────────────────────────────
  load_dataset('facebook/empathetic_dialogues')
      → "Dataset scripts are no longer supported"    (loading script blocked)
  hf_hub_download / direct HTTPS for train.csv
      → 404 Not Found   (CSV files are NOT stored as raw files in the repo;
                          they were generated by the now-blocked script)
  trust_remote_code=True
      → Explicitly rejected in datasets >= 2.20

The fix: HuggingFace Datasets Server REST API
──────────────────────────────────────────────
  GET https://datasets-server.huggingface.co/rows
      ?dataset=facebook/empathetic_dialogues
      &config=default
      &split=train          (or validation / test)
      &offset=0
      &length=1000          (max page size)

  • Returns JSON — no loading script, no token, no auth
  • Works from any environment including Colab free tier
  • ~20 requests for train (~19 533 rows), ~3 for valid/test

Output files written to output_dir
────────────────────────────────────
  dialogues_train.txt / dialogues_valid.txt / dialogues_test.txt
  dialogues_train_emotions.json
  dialogues_valid_emotions.json
  dialogues_test_emotions.json
"""

from __future__ import annotations

import json
import os
import time
import urllib.request
from collections import defaultdict
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Datasets-server downloader
# ─────────────────────────────────────────────────────────────────────────────

_API = 'https://datasets-server.huggingface.co/rows'
_DS  = 'facebook/empathetic_dialogues'


def _fetch_all_rows(hf_split: str, verbose: bool = True) -> list[dict]:
    """
    Stream all rows for one split from the HF Datasets Server API.
    No authentication required.  Returns list of row dicts.
    """
    page_size = 1000
    offset    = 0
    all_rows  = []

    while True:
        url = (f'{_API}?dataset={_DS}&config=default'
               f'&split={hf_split}&offset={offset}&length={page_size}')
        req = urllib.request.Request(
            url,
            headers={'User-Agent': 'python-urllib/3 (EmpatheticPreprocess)'}
        )
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                payload = json.loads(r.read())
        except Exception as e:
            raise RuntimeError(
                f"Datasets Server API failed (split={hf_split}, "
                f"offset={offset}):\n  {e}\n\n"
                "This usually means a transient network issue. Re-run the cell."
            )

        rows = [item['row'] for item in payload.get('rows', [])]
        all_rows.extend(rows)
        total = payload.get('num_rows_total', len(all_rows))

        if verbose:
            print(f"  {hf_split}: {len(all_rows):,} / {total:,} rows …",
                  end='\r', flush=True)

        if len(all_rows) >= total or not rows:
            break
        offset += page_size
        time.sleep(0.05)   # polite pause between pages

    if verbose:
        print(f"  {hf_split}: {len(all_rows):,} rows downloaded.        ")

    return all_rows


# ─────────────────────────────────────────────────────────────────────────────
# Row → dialog conversion
# ─────────────────────────────────────────────────────────────────────────────

def _rows_to_dialogs(rows: list[dict]):
    """
    Group utterance rows by conv_id → sorted dialog turns.

    Returns
    -------
    dialog_lines   : list[str]   DailyDialog-format lines
    emotion_labels : dict[int, str]   {dialog_index → emotion}
    """
    convs    = defaultdict(list)
    emotions = {}

    for row in rows:
        cid  = str(row.get('conv_id', '')).strip()
        text = str(row.get('utterance', '')).strip()
        text = text.replace('_comma_', ',')          # unescape

        if not cid or not text or text == 'nan':
            continue

        try:
            idx = int(row.get('utterance_idx', 0))
        except (TypeError, ValueError):
            idx = 0

        convs[cid].append((idx, text))
        if cid not in emotions:
            em = str(row.get('context', 'unknown')).strip()
            emotions[cid] = em if em else 'unknown'

    dialog_lines   = []
    emotion_labels = {}

    for cid, turns in convs.items():
        turns.sort(key=lambda x: x[0])
        utterances = [t[1] for t in turns
                      if t[1] and t[1].lower() not in ('nan', '')]
        if len(utterances) < 2:
            continue
        line = ' __eou__ '.join(utterances) + ' __eou__'
        idx  = len(dialog_lines)
        dialog_lines.append(line)
        emotion_labels[idx] = emotions.get(cid, 'unknown')

    return dialog_lines, emotion_labels


# ─────────────────────────────────────────────────────────────────────────────
# Main entry point
# ─────────────────────────────────────────────────────────────────────────────

def preprocess_empathetic(output_dir: str, verbose: bool = True) -> dict:
    """
    Download EmpatheticDialogues via the HF Datasets Server API and write
    DailyDialog-format files to output_dir.

    Returns summary dict {split: {'n_dialogs', 'n_pairs', 'emotions'}}.
    Skips splits whose output files already exist (safe to re-run).
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    # HF split name  →  output file stem
    split_map = [
        ('train',      'dialogues_train'),
        ('validation', 'dialogues_valid'),
        ('test',       'dialogues_test'),
    ]

    summary = {}

    for hf_split, stem in split_map:
        txt_path  = os.path.join(output_dir, f'{stem}.txt')
        json_path = os.path.join(output_dir, f'{stem}_emotions.json')

        # Skip if already done
        if (os.path.exists(txt_path)  and os.path.getsize(txt_path)  > 100 and
            os.path.exists(json_path) and os.path.getsize(json_path) > 10):
            print(f"  {hf_split}: already preprocessed → {txt_path}")
            with open(json_path) as f:
                em = set(json.load(f).values())
            with open(txt_path) as f:
                n_diags = sum(1 for _ in f)
            summary[hf_split] = {
                'n_dialogs': n_diags,
                'n_pairs'  : n_diags * 3,   # rough estimate
                'emotions' : sorted(em),
            }
            continue

        if verbose:
            print(f"\nDownloading split: {hf_split} …")

        # 1. Download rows
        rows = _fetch_all_rows(hf_split, verbose=verbose)

        # 2. Convert to dialogs
        dialog_lines, emotion_labels = _rows_to_dialogs(rows)

        # 3. Write output
        with open(txt_path,  'w', encoding='utf-8') as f:
            f.write('\n'.join(dialog_lines))
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(emotion_labels, f)

        unique_emotions = set(emotion_labels.values())
        n_cr = sum(
            max(0, len(line.split(' __eou__ ')) - 2)
            for line in dialog_lines
        )

        summary[hf_split] = {
            'n_dialogs': len(dialog_lines),
            'n_pairs'  : n_cr,
            'emotions' : sorted(unique_emotions),
        }

        if verbose:
            print(f"  {len(dialog_lines):,} dialogs  |  "
                  f"~{n_cr:,} CR pairs  |  "
                  f"{len(unique_emotions)} emotion categories")
            print(f"  → {txt_path}")
            print(f"  → {json_path}")

    if verbose:
        print(f"\nDone. Output dir: {output_dir}")
        ems = summary.get('train', {}).get('emotions', [])
        if ems:
            print(f"Emotion categories ({len(ems)}): {ems}")

    return summary


# ─────────────────────────────────────────────────────────────────────────────
# Stand-alone smoke test
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else '/tmp/empathetic_test'
    summary = preprocess_empathetic(out)
    for sp, info in summary.items():
        print(f"{sp}: {info['n_dialogs']} dialogs  "
              f"{info['n_pairs']} pairs  "
              f"{len(info['emotions'])} emotions")